---
- name: Create /opt/devops/info.txt with content 
  hosts: all
  become: yes

  tasks:
  - name: Ensure /opt/devops directoy exists
    file:
      path: /opt/devops
      state: directory

  - name: Create the info.txt file with content 
    copy:
      dest: /opt/devops/info.txt
      content: Hello from Ansible!
...
