---

- name: Update n1 servers
  hosts: n1
  
  tasks:
  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir
      state: directory

    
  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir1
      state: directory
      

- name: Update n2 servers
  hosts: n2
  
  tasks:
  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir1
      state: directory

<<<<<<< HEAD
  - name: Create Directory
=======
   - name: Create Directory
>>>>>>> 64b9fff81abfe93bf3e9f691270382ba5af0fa6b
    file:
      path: /home/ec2-user/new_dir2
      state: directory

  -  name: update group1 servers
  hosts: g1
  
  tasks:
  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir_group1
      state: directory 

  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir_group2
      state: directory
...
