---

- name: Install HTTP server
  hosts: n2
  become: yes
  
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
    
  -  name: Start Httpd
     service:
      name: httpd
      state: started
      
  -  name: Enaple Httpd
     service:
      name: httpd
      enabled: yes
      
...
