---
- name: Install HTTP server
  hosts: g1
  become: yes
  
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
    when: ansible_distribution =="Amazon"

  -  name: Start Httpd
     service:
      name: httpd
      state: started
      when: ansible_distribution =="Amazon"
      
  -  name: Enaple Httpd
     service:
      name: httpd
      enabled: yes
     when: ansible_distribution =="Amazon"
 
  - name: Install Apache2
    apt:
      name: apache2
      state: present
    when: ansible_distribution =="Ubuntu"
    
  -  name: Start Apache2
     service:
      name: apache2
      state: started
     when: ansible_distribution =="Ubuntu"
      
  -  name: Enaple Apache2
     service:
      name: apache2
      enabled: yes 
      when: ansible_distribution =="Ubuntu" 

...

